import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import { EffectorNext } from '@effector/next';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

import { ReduxDevToolsAdapter } from '@/shared';

// /. IMPORTS

const fontSettings = Roboto({
  weight: '400',
  fallback: ['sans-serif'],
  subsets: ['cyrillic']
});

export const metadata: Metadata = {
  title: 'Social Media Next App',
  description: 'App generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={fontSettings.className}>
        <ReduxDevToolsAdapter />
        <EffectorNext>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </EffectorNext>
      </body>
    </html>
  );
};

export default RootLayout;
